default: &default
  adapter: postgresql
  encoding: unicode
  username: shyam
  password: shyam
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ci_cd_demo_development

test:
  <<: *default
  database: ci_cd_demo_test

# production:
#   <<: *default
#   database: app_production
#   username: shyam
#   password: shyam